# Generated by Django 2.2 on 2021-11-05 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Заголовок')),
                ('content', models.TextField(default='', max_length=3000, verbose_name='Новость')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата редактирования')),
                ('flag_active', models.CharField(choices=[('a', 'active'), ('n', 'not_active')], default='n', max_length=1, verbose_name='Флаг активности')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Имя пользователя')),
                ('text', models.TextField(default='', max_length=3000, verbose_name='Комментарий')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_news.News', verbose_name='Комментируемая новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comments',
            },
        ),
    ]
